import { createContext, useContext, useEffect } from 'react';

const translations = {
  en: {
    appTitle: 'My Route',
    menu: 'Menu',
    back: 'Back',
    routes: 'Routes',
    locations: 'Locations',
    customers: 'Customers',
    settings: 'Settings',
    manageUsers: 'Manage Users',
    addUser: 'Add User',
    deleteUser: 'Delete User',
    confirmDeleteUser: 'Are you sure you want to delete',
    employee: 'Employee',
    admin: 'Admin',
    addCustomer: 'Add Customer',
    searchCustomer: 'Search customer...',
    searchLocation: 'Search location...',
    week: 'Week',
    month: 'Month',
    locationsOnThisDay: 'Locations on this day (edit below)',
    addLocation: 'Add location...',
    close: 'Close',
    open: 'Open',
    removeFromDay: 'Remove from day',
    selected: 'Selected',
    noResultsFor: 'No results for',
    tryDifferentKeywords: 'Try different keywords (name, address, city, type)',
    noLocationsYet: 'No locations yet',
    openMenuAddCustomer: 'Open the menu and tap Add Customer',
    visited: 'Visited',
    pending: 'Pending',
    machine: 'Machine',
    lastVisit: 'Last visit',
    lastCollection: 'Last Collection',
    backToHome: 'Back to Home',
    defaultOrder: 'Default',
    visitedAtBottom: 'Visited ↓',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light mode',
    nightMode: 'Night mode',
    language: 'Language',
    hebrew: 'Hebrew',
    english: 'English',
    addNewCustomer: 'Add New Customer',
    backToLocations: 'Back to Locations',
    backToCustomers: 'Back to Customers',
    addLog: 'Add Log',
    logHistory: 'Log History',
    loading: 'Loading...',
    customerNotFound: 'Customer Not Found',
    locationRemovedOrInvalid: 'This location may have been removed or the link is invalid.',
    businessDetails: 'Business Details',
    businessName: 'Business Name',
    customerName: 'Customer Name',
    fullAddress: 'Full Address',
    locationType: 'Location Type',
    type: 'Type',
    commission: 'Commission',
    commissionRate: 'Commission Rate',
    enterDecimal: 'Enter as decimal (0.40 = 40%)',
    hasChangeMachine: 'Has Change Machine',
    visitDateOptional: 'Visit Date (optional)',
    initialNotes: 'Initial Notes',
    addressZone: 'Address & Zone',
    address: 'Address',
    city: 'City',
    zone: 'Zone',
    state: 'State',
    neighborhood: 'Neighborhood',
    other: 'Other',
    yes: 'Yes',
    no: 'No',
    zipCode: 'Zip Code',
    saveCustomer: 'Save Customer',
    commissionRateHelp: 'Commission this customer pays (e.g. 0.40 = 40%)',
    status: 'Status',
    collectionAmount: 'Total weight',
    coinWeightConverter: 'Coin Weight Converter',
    coinType: 'Coin Type',
    weight: 'Weight',
    giveToCustomer: 'Customer Cut',
    iReceive: 'Half Weight',
    noMoney: 'No Money',
    value: 'Value',
    applyToCollection: 'Apply to Collection',
    notes: 'Notes',
    customerNotes: 'Customer notes',
    logNotes: 'Log notes',
    expand: 'Expand',
    showNotes: 'Show notes',
    collapse: 'Collapse',
    notesPlaceholder: 'Machine refilled. Coin mech jammed. Product restocked...',
    saveComplete: 'Save & Complete',
    locationLog: 'Location Log',
    saveLog: 'Save Log',
    logDate: 'Log date',
    logUser: 'User',
    saveWord: 'Save',
    logWord: 'Log',
    deleteThisCustomer: 'Delete this customer?',
    saveChangesConfirm: 'Save changes?',
    cancel: 'Cancel',
    discardChanges: "Don't save",
    maps: 'Maps',
    waze: 'Waze',
    optionalNotes: 'Optional notes...',
    quartersLabel: 'Quarters (Standard)',
    dimesLabel: 'Dimes',
    nickelsLabel: 'Nickels',
    appVersion: 'Vending Route Manager v1.0',
    home: 'Home',
    loadDemoData: 'Load demo data',
    resetAndLoadDemo: 'Reset & load demo',
    sortBy: 'Sort by',
    sortByCity: 'Cities',
    sortByState: 'States',
    sortByZone: 'Zone',
    sortByAll: 'All',
    bills: 'Bills',
    edit: 'Edit',
    bill50: '50',
    bill20: '20',
    bill10: '10',
    bill5: '5',
    bill1: '1',
    lastVisitSummary: 'Last Visit Summary',
    yearlySummary: 'All-Time Summary',
    visualTheme: 'Visual Theme',
    classic: 'Classic',
    modern: 'Modern',
    // Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to manage your routes',
    login: 'Sign In',
    loginError: 'Invalid username or password',
    username: 'Username',
    password: 'Password',
    usernamePlaceholder: 'Enter username',
    // Home
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    homeSubtitle: "Here's your overview",
    total: 'Total',
    today: 'Today',
    viewAccounts: 'View & manage all accounts',
    addSubtitle: 'Register a new location',
    todaysEarnings: "Today's $",
    recentActivity: 'Recent Activity',
    recentActivitySub: 'Latest visits',
    tasksReminders: 'Tasks & Reminders',
    tasksRemindersSub: 'Follow-ups and due items',
    mapOverview: 'Map Overview',
    mapOverviewSub: 'Status by area',
    totalEarnings: 'Total Earnings',
    totalEarningsSub: 'All-time revenue',
    manageUsersSub: 'Team & permissions',
    settingsSub: 'Preferences & account',
    reportsSub: 'Charts & analytics',
    addCustomerSub: 'Register new location',
    customersSub: 'View & manage all',
    noRecentActivity: 'No recent activity yet',
    // Menu
    hi: 'Hi',
    search: 'Search...',
    logout: 'Log Out',
    confirmLogout: 'Are you sure you want to log out?',
    // Manage Users
    online: 'Online',
    neverLoggedIn: 'Never',
    justNow: 'Just now',
    minutesAgo: 'min ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    yesterday: 'Yesterday',
    delete: 'Delete',
    save: 'Save',
    textSize: 'Text Size',
    textSizeSmall: 'Small',
    textSizeRegular: 'Regular',
    textSizeLarge: 'Large',
    reports: 'Reports',
    reportsTitle: 'Reports Dashboard',
    dateRange: 'Date Range',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    from: 'From',
    to: 'To',
    totalWeight: 'Total Weight',
    halfWeight: 'Half Weight',
    customerCut: 'Customer Cut',
    totalVisits: 'Total Visits',
    totalCustomers: 'Total Customers',
    incomeOverTime: 'Income Over Time',
    topCustomers: 'Top 10 Customers',
    distributionByZone: 'Distribution by Zone',
    periodComparison: 'Period Comparison',
    currentPeriod: 'Current Period',
    previousPeriod: 'Previous Period',
    change: 'Change',
    decliningCustomers: 'Declining Customers',
    noVisitsInPeriod: 'No visits in selected period',
    exportPdf: 'Export PDF',
    exportCsv: 'Export CSV',
    allCollectors: 'All Collectors',
    collector: 'Collector',
    noDataAvailable: 'No data available',
    addLogsToSeeReports: 'Add logs to see reports',
    summaryReport: 'Summary Report',
    generatedOn: 'Generated on',
    period: 'Period',
    visits: 'Visits',
    filterBy: 'Filter by',
    byZone: 'Zone',
    byLocation: 'Location',
    distributionByLocation: 'Distribution by Location',
    reportSearchZone: 'Search by zone...',
    reportSearchLocation: 'Search by location...',
    overall: 'Overall',
    byZoneFilter: 'By Zone',
    filterByLabel: 'Filter by',
    byVisits: 'By Visits',
    byDate: 'By Date',
    lastVisits: 'Last',
    visitsCount: 'visits',
    custom: 'Custom',
    presetMonth: 'Month',
    threeMonths: '3 months',
    sixMonths: '6 months',
    year: 'Year',
    allTime: 'All-time',
    lastNVisits: 'Last N visits',
    taskTitle: 'Task title',
    taskCustomer: 'Customer',
    taskSearchCustomer: 'Search customer...',
    taskPriority: 'Priority',
    taskDueDate: 'Due date',
    taskNotes: 'Notes',
    taskStatusOpen: 'Open',
    taskStatusInProgress: 'In Progress',
    taskStatusDone: 'Done',
    taskStatusSnoozed: 'Snoozed',
    taskFilterAll: 'All',
    taskFilterOverdue: 'Overdue',
    taskFilterToday: 'Today',
    taskFilterDone: 'Done',
    addTask: 'Add Task',
    noTasksYet: 'No tasks right now',
    noTasksHint: 'Create a manual task or rely on auto reminders.',
    saveTask: 'Save Task',
    snooze24h: 'Snooze 24h',
    markDone: 'Mark done',
    reopen: 'Reopen',
    remove: 'Remove',
    autoTaskNoVisitTitle: 'No visit in a while',
    autoTaskNoVisitBody: 'No visit in the last {days} days',
    autoTaskNoMoneyTitle: 'No money streak',
    autoTaskNoMoneyBody: '{count} visits in a row with no collection',
    mapSearchPlaceholder: 'Search customer or zone...',
    urgentOnly: 'Urgent only',
    openInCustomers: 'Open in Customers',
    openInMaps: 'Open in Maps',
    statusVisitedToday: 'Visited today',
    statusMedium: 'Medium',
    statusPending: 'Pending',
    statusNoAction: 'No action needed',
    statusUrgent: 'Urgent',
    noMapResults: 'No locations match these filters',
    notifications: 'Notifications',
    notificationsSub: 'Alerts & updates',
    notifAll: 'All',
    notifUnread: 'Unread',
    notifAlerts: 'Alerts',
    notifRevenue: 'Revenue',
    notifVisits: 'Visits',
    notifMarkAllRead: 'Mark all as read',
    notifMarkRead: 'Read',
    notifDismiss: 'Dismiss',
    notifViewCustomer: 'View',
    notifEmpty: 'No notifications',
    notifEmptyHint: 'You\'re all caught up! Notifications appear here automatically.',
    notifHigh: 'Urgent',
    notifJustNow: 'Just now',
    notifYesterday: 'Yesterday',
    notifDaysAgo: 'days ago',
    notifWeeksAgo: 'weeks ago',
    notifMonthsAgo: 'months ago',
    notifUrgentNoVisit: 'Urgent: No visit in a long time',
    notifVisitReminder: 'Visit reminder',
    notifDaysNoVisit: 'days since last visit',
    notifNoRevenue: 'No revenue alert',
    notifConsecutiveEmpty: 'consecutive empty collections',
    notifCollectionRecorded: 'Collection recorded',
    // Privacy
    privacyTitle: 'Privacy',
    privacyProfileVisibility: 'Who can see your profile',
    privacyEveryone: 'Everyone',
    privacyTeamOnly: 'Team',
    privacyPrivate: 'Private',
    privacyShowEmail: 'Show email to others',
    privacyShowActivity: 'Show my activity status',
    privacyAdminOnly: 'Admin Only',
    privacyPermissionsDesc: 'Control what employees can access',
    privacyPermViewCustomers: 'Employees can view all customers',
    privacyPermViewReports: 'Employees can view reports',
    privacyPermEditLogs: 'Employees can edit logs',
    privacyDownloadData: 'Download My Data',
    // Security
    securityTitle: 'Security & Passwords',
    secChangePassword: 'Change Password',
    secCurrentPassword: 'Current password',
    secNewPassword: 'New password',
    secConfirmPassword: 'Confirm new password',
    secUpdatePassword: 'Update Password',
    secPwTooShort: 'Password must be at least 6 characters',
    secPwMismatch: 'Passwords do not match',
    secPwWrongCurrent: 'Current password is incorrect',
    secPwError: 'Failed to update password',
    secPwSuccess: 'Password updated successfully!',
    secTwoFactor: 'Two-Factor Auth',
    secTwoFactorDesc: 'Extra security for your account',
    secSessionTimeout: 'Auto-lock after inactivity',
    secNever: 'Never',
    secActiveSessions: 'Active Sessions',
    secCurrentDevice: 'This device',
    secActiveNow: 'Active now',
    // Account
    accTitle: 'Account Settings',
    accPersonalInfo: 'Personal Information',
    accName: 'Full Name',
    accNamePlaceholder: 'Enter your name',
    accEmail: 'Email',
    accEmailHint: 'Email cannot be changed here',
    accPhone: 'Phone Number',
    accPhonePlaceholder: 'Enter phone number',
    accSaveChanges: 'Save Changes',
    accSaving: 'Saving...',
    accSaved: 'Changes saved successfully!',
    accSaveError: 'Failed to save changes',
    accNameRequired: 'Name is required',
    accAvatarTooLarge: 'Image must be under 2MB',
    accAccountInfo: 'Account Info',
    accRole: 'Role',
    accUsername: 'Username',
    accMemberSince: 'Member Since',
    displayPreferences: 'Display Preferences',
    // Admin Dashboard - Manage Users
    teamDashboard: 'Team Dashboard',
    searchUsers: 'Search by name, role, area...',
    totalMembers: 'Total',
    onlineNow: 'Online',
    onBreakNow: 'On Break',
    adminsCount: 'Admins',
    allRoles: 'All Roles',
    technician: 'Technician',
    routeDriver: 'Route Driver',
    moneyCollector: 'Collector',
    allStatuses: 'All Status',
    onShift: 'On Shift',
    onBreak: 'On Break',
    offline: 'Offline',
    sortByName: 'Name',
    sortByRole: 'Role',
    sortByLastSeen: 'Last Seen',
    sortByStatus: 'Status',
    storesVisited: 'Visited',
    openTickets: 'Tickets',
    assignRole: 'Assign Role',
    vehicleAssignment: 'Vehicle',
    vehiclePlaceholder: 'e.g. Van #3',
    fieldEquipment: 'Equipment',
    equipmentPlaceholder: 'Add item...',
    areaAssignment: 'Area',
    areaPlaceholder: 'e.g. Downtown',
    viewAuditTrail: 'Activity Log',
    auditTrail: 'Audit Trail',
    auditLogin: 'Signed in',
    auditLogout: 'Signed out',
    auditVisit: 'Location visit',
    auditCollection: 'Cash collected',
    auditRepair: 'Machine repair',
    auditProfileUpdate: 'Profile updated',
    auditRoleChange: 'Role changed',
    auditAccountCreated: 'Account created',
    noAuditEvents: 'No activity recorded yet',
    saveChanges: 'Save',
    saving: 'Saving...',
    saved: 'Saved!',
    noUsersFound: 'No users match your filters',
    quickKPIs: 'Daily Performance',
    // Route Optimization
    optimizeRoute: 'Route Order',
    // Inactive
    inactive: 'Inactive',
    active: 'Active',
    markInactive: 'Mark as Inactive',
    markActive: 'Mark as Active',
    confirmMarkInactive: 'Mark this customer as inactive? (e.g. machine collected)',
    confirmMarkActive: 'Reactivate this customer?',
    inactiveCustomer: 'Inactive Customer',
    showInactive: 'Show Inactive',
    hideInactive: 'Hide Inactive',
    machineCollected: 'Machine Collected',
    enterPassword: 'Enter password to continue',
    wrongPassword: 'Wrong password',
    confirm: 'Confirm',
  },
};

// Weekday labels for calendar (Sun–Sat)
const WEEKDAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  useEffect(() => {
    document.documentElement.lang = 'en';
    document.documentElement.dir = 'ltr';
  }, []);

  const t = (key) => translations.en[key] ?? key;
  const weekdayLabels = WEEKDAY_LABELS;
  const monthNames = MONTH_NAMES;

  return (
    <LanguageContext.Provider
      value={{
        language: 'en',
        setLanguage: () => {},
        t,
        isRtl: false,
        isTransitioning: false,
        weekdayLabels,
        monthNames,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
