import { createContext, useContext, useEffect } from 'react';

const translations = {
  en: {
    appTitle: 'My Route',
    menu: 'Menu',
    back: 'Back',
    routes: 'Routes',
    locations: 'Locations',
    customers: 'Customers',
    settings: 'Settings',
    manageUsers: 'Manage Users',
    addUser: 'Add User',
    deleteUser: 'Delete User',
    confirmDeleteUser: 'Are you sure you want to delete',
    employee: 'Employee',
    admin: 'Admin',
    addCustomer: 'Add Customer',
    searchCustomer: 'Search customer...',
    searchLocation: 'Search location...',
    week: 'Week',
    month: 'Month',
    locationsOnThisDay: 'Locations on this day (edit below)',
    addLocation: 'Add location...',
    close: 'Close',
    open: 'Open',
    removeFromDay: 'Remove from day',
    selected: 'Selected',
    noResultsFor: 'No results for',
    tryDifferentKeywords: 'Try different keywords (name, address, city, type)',
    noLocationsYet: 'No locations yet',
    openMenuAddCustomer: 'Open the menu and tap Add Customer',
    visited: 'Visited',
    pending: 'Pending',
    machine: 'Machine',
    lastVisit: 'Last visit',
    lastCollection: 'Last Collection',
    backToHome: 'Back to Home',
    defaultOrder: 'Default',
    visitedAtBottom: 'Visited ↓',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light mode',
    nightMode: 'Night mode',
    language: 'Language',
    hebrew: 'Hebrew',
    english: 'English',
    addNewCustomer: 'Add New Customer',
    backToLocations: 'Back to Locations',
    backToCustomers: 'Back to Customers',
    addLog: 'Add Log',
    logHistory: 'Log History',
    loading: 'Loading...',
    customerNotFound: 'Customer Not Found',
    locationRemovedOrInvalid: 'This location may have been removed or the link is invalid.',
    businessDetails: 'Business Details',
    businessName: 'Business Name',
    customerName: 'Customer Name',
    fullAddress: 'Full Address',
    locationType: 'Location Type',
    type: 'Type',
    commission: 'Commission',
    commissionRate: 'Commission Rate',
    enterDecimal: 'Enter as decimal (0.40 = 40%)',
    hasChangeMachine: 'Has Change Machine',
    visitDateOptional: 'Visit Date (optional)',
    initialNotes: 'Initial Notes',
    addressZone: 'Address & Zone',
    address: 'Address',
    city: 'City',
    zone: 'Zone',
    state: 'State',
    neighborhood: 'Neighborhood',
    other: 'Other',
    yes: 'Yes',
    no: 'No',
    zipCode: 'Zip Code',
    saveCustomer: 'Save Customer',
    commissionRateHelp: 'Commission this customer pays (e.g. 0.40 = 40%)',
    status: 'Status',
    collectionAmount: 'Total weight',
    coinWeightConverter: 'Coin Weight Converter',
    coinType: 'Coin Type',
    weight: 'Weight',
    giveToCustomer: 'Customer Cut',
    iReceive: 'Half Weight',
    noMoney: 'No Money',
    value: 'Value',
    applyToCollection: 'Apply to Collection',
    notes: 'Notes',
    customerNotes: 'Customer notes',
    logNotes: 'Log notes',
    expand: 'Expand',
    showNotes: 'Show notes',
    collapse: 'Collapse',
    notesPlaceholder: 'Machine refilled. Coin mech jammed. Product restocked...',
    saveComplete: 'Save & Complete',
    locationLog: 'Location Log',
    saveLog: 'Save Log',
    logDate: 'Log date',
    logUser: 'User',
    saveWord: 'Save',
    logWord: 'Log',
    deleteThisCustomer: 'Delete this customer?',
    saveChangesConfirm: 'Save changes?',
    cancel: 'Cancel',
    discardChanges: "Don't save",
    maps: 'Maps',
    waze: 'Waze',
    optionalNotes: 'Optional notes...',
    quartersLabel: 'Quarters (Standard)',
    dimesLabel: 'Dimes',
    nickelsLabel: 'Nickels',
    appVersion: 'Vending Route Manager v1.0',
    home: 'Home',
    loadDemoData: 'Load demo data',
    resetAndLoadDemo: 'Reset & load demo',
    sortBy: 'Sort by',
    sortByCity: 'Cities',
    sortByState: 'States',
    sortByZone: 'Zone',
    sortByAll: 'All',
    bills: 'Bills',
    edit: 'Edit',
    bill50: '50',
    bill20: '20',
    bill10: '10',
    bill5: '5',
    bill1: '1',
    lastVisitSummary: 'Last Visit Summary',
    yearlySummary: 'All-Time Summary',
    visualTheme: 'Visual Theme',
    classic: 'Classic',
    modern: 'Modern',
    // Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Sign in to manage your routes',
    login: 'Sign In',
    loginError: 'Invalid username or password',
    username: 'Username',
    password: 'Password',
    usernamePlaceholder: 'Enter username',
    // Home
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    homeSubtitle: "Here's your overview",
    total: 'Total',
    today: 'Today',
    viewAccounts: 'View & manage all accounts',
    addSubtitle: 'Register a new location',
    // Menu
    hi: 'Hi',
    search: 'Search...',
    logout: 'Log Out',
    confirmLogout: 'Are you sure you want to log out?',
    // Manage Users
    online: 'Online',
    neverLoggedIn: 'Never',
    justNow: 'Just now',
    minutesAgo: 'min ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    yesterday: 'Yesterday',
    delete: 'Delete',
    save: 'Save',
    textSize: 'Text Size',
    textSizeSmall: 'Small',
    textSizeRegular: 'Regular',
    textSizeLarge: 'Large',
    reports: 'Reports',
    reportsTitle: 'Reports Dashboard',
    dateRange: 'Date Range',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    from: 'From',
    to: 'To',
    totalWeight: 'Total Weight',
    halfWeight: 'Half Weight',
    customerCut: 'Customer Cut',
    totalVisits: 'Total Visits',
    totalCustomers: 'Total Customers',
    incomeOverTime: 'Income Over Time',
    topCustomers: 'Top 10 Customers',
    distributionByZone: 'Distribution by Zone',
    periodComparison: 'Period Comparison',
    currentPeriod: 'Current Period',
    previousPeriod: 'Previous Period',
    change: 'Change',
    decliningCustomers: 'Declining Customers',
    noVisitsInPeriod: 'No visits in selected period',
    exportPdf: 'Export PDF',
    noDataAvailable: 'No data available',
    addLogsToSeeReports: 'Add logs to see reports',
    summaryReport: 'Summary Report',
    generatedOn: 'Generated on',
    period: 'Period',
    visits: 'Visits',
    filterBy: 'Filter by',
    byZone: 'Zone',
    byLocation: 'Location',
    distributionByLocation: 'Distribution by Location',
  },
};

// Weekday labels for calendar (Sun–Sat)
const WEEKDAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  useEffect(() => {
    document.documentElement.lang = 'en';
    document.documentElement.dir = 'ltr';
  }, []);

  const t = (key) => translations.en[key] ?? key;
  const weekdayLabels = WEEKDAY_LABELS;
  const monthNames = MONTH_NAMES;

  return (
    <LanguageContext.Provider
      value={{
        language: 'en',
        setLanguage: () => {},
        t,
        isRtl: false,
        isTransitioning: false,
        weekdayLabels,
        monthNames,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
